services:
  fluentbit:
    image: ${FLUENT_BIT_IMAGE:-fluent/fluent-bit:3.2.10}
    container_name: fluentbit
    user: "0:0"
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./enrich.lua:/fluent-bit/etc/enrich.lua:ro
      - ./parsers.conf:/fluent-bit/etc/parsers.conf:ro
      - ./state:/state
      - /weblogic_domain/domains/base_domain/servers/AdminServer/logs:/logs/weblogic:ro
    command: >
      /fluent-bit/bin/fluent-bit
      -c /fluent-bit/etc/fluent-bit.conf
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
