[SERVICE]
    Flush       5
    Daemon      Off
    Log_Level   info
    Parsers_File parsers.conf

[INPUT]
    Name              tail
    Path              /logs/weblogic/*.log
    Tag               weblogic.logs
    Refresh_Interval  5
    Read_from_Head    false
    Mem_Buf_Limit     50MB
    Skip_Long_Lines   On
    DB                /tmp/flb_weblogic.db
    Rotate_Wait       30

[FILTER]
    Name   grep
    Match  weblogic.logs
    Regex  log (ERROR|Exception|BEA-149038|BEA-141052|BEA-000360|Connection refused|OutOfMemory|StuckThreadMaxTime|SocketTimeoutException)

[FILTER]
    Name modify
    Match weblogic.logs
    Copy log rawlog

[FILTER]
    Name   record_modifier
    Match  weblogic.logs
    Record appsrv APPSRV_UNIQUE
    Record appsrvid APPSRV_ID
    Record srvid SERVER_ID
    Record srvtype weblogic
    Record inttoken INTERNAL_TOKEN

[FILTER]
    Name throttle
    Match weblogic.logs
    Rate 5
    Window 30

[FILTER]
    Name       parser
    Match      weblogic.logs
    Key_Name   log
    Parser     weblogic_error
    Reserve_Data On

[FILTER]
    Name lua
    Match weblogic.logs
    script /fluent-bit/etc/enrich.lua
    call enrich_record

[OUTPUT]
    Name        http
    Match       weblogic.logs
    Host        MIDLEO.CORE_DNS
    Port        443
    URI         /pubapi/monalert
    Format      json
    Json_date_key false
    tls         On
    tls.verify  Off
    Retry_Limit False