midagent_vars:
   agent_install_dir: '/var/midleoagent/'
   python_install_dir: '/usr/bin/python3'
   midleo_mwuser: 'mwadmin'
   weblogic_home: '/opt/oracle/middleware'
   ibmmq_home: '/opt/mqm'
   ibmace_home: '/opt/ibm/ace-12/server'
   ibmiib_home: '/opt/ibm/iib-10.0.0.11/server'
   tomcat_home: ''
   jboss_home: ''
   ibmwas_home: ''
   rabbitmq_home: ''
   tibcoems_home: ''
   activemq_home: ''
   kafka_home: ''
   msiis_home: ''
