#send IIB messages to logstash
:msg, contains, "IBM Integration Bus" action(type="omfwd" target="logstash" port="15044" protocol="udp"
            action.resumeRetryCount="-1" template="json-template"
            queue.type="linkedList" queue.size="10000"
            queue.filename="midleo_iib_logstash" queue.saveOnShutdown="on")
#remove all IIB messages from subsequent logs
:msg, contains, "IBM Integration Bus" stop
