---
- set_fact:
    agent_unique_id: "{{ lookup('password', '/dev/null length=16 chars=hexdigits') }}"
    agent_install_dir: "/var/midleoagent"
- name: "create midleoagent folder"
  win_file:
    path: "{{agent_install_dir}}"
    state: directory
- name: "creage agentconfig"
  win_template:
    src: templates/agentConfig.json.j2
    dest: "{{agent_install_dir}}/agentConfig.json"
- name: "upload python scripts"
  win_template:
    src: '{{ item.src }}'
    dest: "{{agent_install_dir}}/{{ item.path }}"