---
- set_fact:
    agent_unique_id: "{{ lookup('password', '/dev/null length=16 chars=hexdigits') }}"
    agent_install_dir: "D:/apps/midleoagent/"
    python_install_dir: "D:/apps/Python"
- name: "create midleoagent folder"
  win_file:
    path: "{{item}}"
    state: directory
  loop:
    - "{{agent_install_dir}}"
    - "{{agent_install_dir}}modules"
    - "{{agent_install_dir}}logs"
    - "{{agent_install_dir}}config"
- name: "creage agent"
  win_template:
    src: templates/python/midleo_client.py
    dest: "{{agent_install_dir}}midleo_client.py"
- name: "creage agentconfig"
  win_template:
    src: templates/agentConfig.json.j2
    dest: "{{agent_install_dir}}config/agentConfig.json"
- name: "upload python scripts"
  win_template:
    src: '{{ item.src }}'
    dest: "{{agent_install_dir}}modules/{{ item.path }}"
  with_filetree: templates/python/modules
- name: Install python packages
  win_shell: |
    {{python_install_dir}}\\python -m pip install --upgrade pip
    pip install psutil
    pip install py-cpuinfo
    pip install dnspython
    pip install requests
    pip install pycryptodome
    pip install netifaces
- name: create scheduled task to run python agent on boot
  win_scheduled_task:
    name: midleoagent
    description: Run the midleoagent on boot
    actions:
    - path: "{{python_install_dir}}/python.exe"
      arguments: "{{agent_install_dir}}midleo_client.py"
      working_directory: "{{agent_install_dir}}"
    triggers:
    - type: boot
    username: SYSTEM
    run_level: highest
    state: present
...